import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-hero-section ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <div className="flex flex-col justify-center items-center mt-16">
            <div className="w-[500px] rounded-2xl bg-[var(--color-bg-body)] p-3">
              {children}
            </div>
        </div>

      </body>
    </html>
  );
}
